swagger:
    show: true
email:
    send:
        exception: true
eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    client:
        service-url:
            defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/
        registry-fetch-interval-seconds: 5
        healthcheck:
            enabled: true
spring:
    redis:
        host: r-wz98e22ea634dee4.redis.rds.aliyuncs.com
        port: 6379
        password: Hr_yjPaW4_560
        timeout: 10000
oss:
    accessKeyId: LTAIf4FsbF2QvPkQ
    accessKeySecret: PlnlqqQNNU32g1nOgUjytzjOiKMGOy
    endpoint: oss-cn-shenzhen.aliyuncs.com
    domain: test-static.hryjmall.com
    backetName: hryj-test